#!/bin/sh

file=$HOME/dotfiles/config/i3/scripts/autoload.txt

out=$(xclip -out -selection primary)
$(grep -xq "$out" $file)
if [ $? == 0 ]; then
    [ ! -z "${out// }" ] && sed -z -i "s|$out\n||g" $file
    notify-send -u critical "Entry $out removed from autoload list"
elif [ ! -z "${out// }" ]; then
    printf "$out\n" >> $file
    notify-send "Link $out added to autoload links."
fi
