#!/bin/sh

search_online() {
if [ $1 == "mondo" ]; then
    brave www.mondo.rs
elif [ $1 == "mf" ]; then
    brave www.github.com/mainflux/mainflux
elif [ $1 == "fb" ]; then
    brave www.facebook.com
elif [ $1 == "wa" ]; then
    brave https://web.whatsapp.com
else
    # URL-encode.
    q=$(echo $@ | sed "s/ /+/g; s/\%/\%25/g")
    brave https://duckduckgo.com/?q=$q
fi
}

param=$(dmenu_path | dmenu "$@"-fn 'DejaVu Sans Mono Nerd Font:size=14' -nb '#004D40' -sb '#004D40' -i -p "Search:")
if $(type $param); then
    $param | ${SHELL:-"usr/bin/zsh"} &
else
search_online $param
fi
