source ~/dotfiles/zsh/options.zsh
source ~/dotfiles/zsh/exports.zsh
source ~/dotfiles/zsh/prompt.zsh
source ~/dotfiles/zsh/autosuggestions.zsh
source ~/dotfiles/zsh/completion.zsh
source ~/dotfiles/zsh/aliases.zsh
source ~/dotfiles/zsh/bindings.zsh
source ~/dotfiles/zsh/history.zsh
source ~/dotfiles/zsh/theme.zsh
source ~/dotfiles/powerlevel9k/powerlevel9k.zsh-theme
source <(kubectl completion zsh)
